/**
 * Lib
 * Library setup
 *
 * OpenAPI spec version: 1.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Book (
  id: Int,
  title: String,
  description: String,
  author: Author,
  link: String,
  pubDate: Option[String] = None
) extends ApiModel


